#!/usr/bin/env bash

case $1 in
    config ) shift
          tsc-config $@
          exit
          ;;
    ssc ) shift
          tsc-ssc $@
          exit
          ;;
    update ) shift
             tsc-update $@
             exit
             ;;
    health ) shift
             tsc-health $@
             exit
             ;;
    version ) shift
              tsc-version $@
              exit
              ;;
    * ) echo "Unkown subcommand tscommand-$1"
        exit 1
        ;;
esac